# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bac08c771ecf563fae4acd5b5bb679bf8e2ee6697a52d2e00a596cac5b75bbef0da0137ddfb3e589b798b04536692472b4bbbeb866d40bb8e59d955412570d40

test:
  secret_key_base: 98974425a3a2e4e25fbc541f30bc943beb923cf9c4b620a966b1f8fe7d222a9f07297a2c5aff2e1f54b29e389071550870ba559ac0736f6264349bba3eb26263

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
